### ISSUE TITLE
CAA records getting pulled think they're double quoted.

### ISSUE THREAD

**Issue by ckdbagwell** [octodns/octodns-edgedns#48]
We recently updated to 0.0.4 to get CAA support.  Previously we were just creating them manually because they don't pop up very often.

However, now that we have them, they're weird:

All of them end up looking like this:

```
********************************************************************************
* somedomain.com.
********************************************************************************
* akamai (AkamaiProvider)
*   Update
*     <CaaRecord CAA 300, somedomain.com., ['0 iodef ""mailto:domains-caa@somedomain.com."', '0 issue ""digicert.com""', '0 issuewild ""digicert.com""']> ->
*     <CaaRecord CAA 300, somedomain.com., ['0 iodef "mailto:domains-caa@somedomain.com.', '0 issue "digicert.com"', '0 issuewild "digicert.com"']> (config)
*   Update
*     <CaaRecord CAA 300, admin.somedomain.com., ['0 iodef ""mailto:domains-caa@somedomain.com."', '0 issue ""digicert.com""', '0 issue ""pki.goog""', '0 issuewild ""digicert.com""']> ->
*     <CaaRecord CAA 300, admin.somedomain.com., ['0 iodef "mailto:domains-caa@somedomain.com.', '0 issue "digicert.com"', '0 issue "pki.goog"', '0 issuewild "digicert.com"']> (config)
*   Update
*     <CaaRecord CAA 300, corp.somedomain.com., ['0 iodef ""mailto:domains-caa@somedomain.com."', '0 issue ""amazonaws.com""', '0 issue ""digicert.com""', '0 issue ""pki.goog""', '0 issuewild ""digicert.com""']> ->
*     <CaaRecord CAA 300, corp.somedomain.com., ['0 iodef "mailto:domains-caa@somedomain.com.', '0 issue "amazonaws.com"', '0 issue "digicert.com"', '0 issue "pki.goog"', '0 issuewild "digicert.com"']> (config)
*   Summary: Creates=0, Updates=3, Deletes=0, Existing Records=896
```

Even after 'doit' they continue to pop up as Updates.  This is the record _from_ akamai.  We tried mucking around with quotes and stuff in our yaml, but it doesn't seem to matter.  

Wondering what we're doing wrong here.

**Comment by ross** [comment]
Its likely something is going awry with one or both of the deserialization/serialization methods:

https://github.com/octodns/octodns-edgedns/blob/02c5343d54e55e1f5dd36b82d3de7400454016ba/octodns_edgedns/__init__.py#L329-L334

or

https://github.com/octodns/octodns-edgedns/blob/02c5343d54e55e1f5dd36b82d3de7400454016ba/octodns_edgedns/__init__.py#L417-L426

Unfortunately I don't have access to EdgeDNS so it'll be up to someone who does to to dig into the problem and file a PR. The original PR that added support was https://github.com/octodns/octodns-edgedns/pull/16. It's likely that the tests will need some updates as well.

**Comment by ross** [comment]
> [ckdbagwell](https://github.com/ckdbagwell) closed this as [completed](https://github.com/octodns/octodns-edgedns/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [35 minutes ago](https://github.com/octodns/octodns-edgedns/issues/48#event-13767637837)

Did you figure out what was up?
